### PR TITLE
Update website pricing and payment handling information

### PR DESCRIPTION
**Pull request by stevepetebruce**
Updated index page to reflect new pricing model and payment handling.

Removed code line spacing and unnecessary returns in web copy.

Previous copy which related to a percentage charge:
Screenshot 2019-03-13 at 17 42 24

Updated copy to represent the new flat fee.
Screenshot 2019-03-13 at 17 43 42

### CODE REVIEW

**Comment by AlanDonohoe** [comment]
I'm getting errors when I try to open the site locally:

image

**Comment by AlanDonohoe** [comment]
Will need to rebase this branch with master to include the fixes. Also there's conflicting changes in index.html....

**Comment by AlanDonohoe** [comment]
This would of been perfect to have had a screenshot showing the before and after... 
Harder to see the changes when it's in the code.

**Comment by stevepetebruce** [comment]
Rebased and added screenshots in the pull request to visualise changes.

**Comment by AlanDonohoe** [comment]
I think we can improve the pricing card but happy to merge this in for now. Nice one @stevepetebruce !

**Pull request merged**
